#include <iostream>

/*
    Main file automatically generated by Bruno. Use this as an
    entry point to an application.
*/
int main(int argc, char **argv) {
    std::cout << "Hello world!!!" << std::endl;
    
    return 0;
}
